// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFO81CkYgcnx_8e2xEnBZ8AiJm7Rot-k',
    appId: '1:219689938673:web:2a19504cd43aca15b84350',
    messagingSenderId: '219689938673',
    projectId: 'online-file-transfer-a8ab2',
    authDomain: 'online-file-transfer-a8ab2.firebaseapp.com',
    storageBucket: 'online-file-transfer-a8ab2.firebasestorage.app',
    measurementId: 'G-YNMXK8QZGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt79lKIED-tigvubk-rWP6INR5eHQbLoQ',
    appId: '1:219689938673:android:39fa5f0b45f1ff4bb84350',
    messagingSenderId: '219689938673',
    projectId: 'online-file-transfer-a8ab2',
    storageBucket: 'online-file-transfer-a8ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZlmg9fZcfPAKeRcdnmvm20Ry96Y9iAI',
    appId: '1:219689938673:ios:b2d5f35e7bd9453fb84350',
    messagingSenderId: '219689938673',
    projectId: 'online-file-transfer-a8ab2',
    storageBucket: 'online-file-transfer-a8ab2.firebasestorage.app',
    iosBundleId: 'com.devomni.onlineFileTransfer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZlmg9fZcfPAKeRcdnmvm20Ry96Y9iAI',
    appId: '1:219689938673:ios:b2d5f35e7bd9453fb84350',
    messagingSenderId: '219689938673',
    projectId: 'online-file-transfer-a8ab2',
    storageBucket: 'online-file-transfer-a8ab2.firebasestorage.app',
    iosBundleId: 'com.devomni.onlineFileTransfer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiFO81CkYgcnx_8e2xEnBZ8AiJm7Rot-k',
    appId: '1:219689938673:web:b541440267273397b84350',
    messagingSenderId: '219689938673',
    projectId: 'online-file-transfer-a8ab2',
    authDomain: 'online-file-transfer-a8ab2.firebaseapp.com',
    storageBucket: 'online-file-transfer-a8ab2.firebasestorage.app',
    measurementId: 'G-C7R2P5LSPY',
  );
}
